// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqvQ2mw5YFrjM0uLdKz-uSrFQw1cMjEEU',
    appId: '1:437521744987:web:112c834893b9589f0b2b7e',
    messagingSenderId: '437521744987',
    projectId: 'finaly-267ce',
    authDomain: 'finaly-267ce.firebaseapp.com',
    storageBucket: 'finaly-267ce.firebasestorage.app',
    measurementId: 'G-ERHRWH831X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGj63WKOfiiQMO8ttOmCZwHKnJfkNFvfE',
    appId: '1:437521744987:android:0ae4aaf78d073fcf0b2b7e',
    messagingSenderId: '437521744987',
    projectId: 'finaly-267ce',
    storageBucket: 'finaly-267ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtRi-WGnofUPeOpd_TwqhGHn_awwV7Bds',
    appId: '1:437521744987:ios:67a1cbbe289636350b2b7e',
    messagingSenderId: '437521744987',
    projectId: 'finaly-267ce',
    storageBucket: 'finaly-267ce.firebasestorage.app',
    iosBundleId: 'com.example.fainalyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtRi-WGnofUPeOpd_TwqhGHn_awwV7Bds',
    appId: '1:437521744987:ios:67a1cbbe289636350b2b7e',
    messagingSenderId: '437521744987',
    projectId: 'finaly-267ce',
    storageBucket: 'finaly-267ce.firebasestorage.app',
    iosBundleId: 'com.example.fainalyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqvQ2mw5YFrjM0uLdKz-uSrFQw1cMjEEU',
    appId: '1:437521744987:web:41a8a562ca9e44280b2b7e',
    messagingSenderId: '437521744987',
    projectId: 'finaly-267ce',
    authDomain: 'finaly-267ce.firebaseapp.com',
    storageBucket: 'finaly-267ce.firebasestorage.app',
    measurementId: 'G-WWQ76670KM',
  );
}
